client:
  url: http://localhost:3000
  api_key: REPLACE_ME
upload:
  upload_path: /tmp/incoming
  rsync_point: localhost:incoming
  storage_path: /tmp/pfdr/storage/
validation:
  external:
    audio: "/path/to/validator"
    video: "/path/to/validator"
  bagger_profile:
    digital: "http://uri_to_bagger_profile"


